brew install awscli
brew install byobu
brew install cairo
brew install cask
brew install coreutils
brew install cowsay
brew install dtrx
brew install emacs
brew install fontconfig
brew install fortune
brew install freetype
brew install gawk
brew install gcc
brew install gdbm
brew install gettext
brew install git
brew install git-extras
brew install glib
brew install gmp
brew install gnu-sed
brew install htop-osx
brew install isl
brew install jpeg
brew install lftp
brew install libevent
brew install libffi
brew install libmpc
brew install libpng
brew install libtiff
brew install libyaml
brew install mariadb
brew install maven
brew install mpfr
brew install mtr
brew install newt
brew install nmap
brew install node
brew install openssl
brew install p7zip
brew install parallel
brew install pcre
brew install perl
brew install pixman
brew install popt
brew install pv
brew install python
brew install python3
brew install r
brew install ranger
brew install readline
brew install reattach-to-user-namespace
brew install ruby
brew install s-lang
brew install sqlite
brew install tmux
brew install tree
brew install unrar
brew install vim
brew install wget
brew install xz
brew install zsh
